### ISSUE TITLE
Trying to build from your sources and failing on the same issue..

### ISSUE THREAD

**Issue by mannp** [Sony-MSM8994-Dev/android_device_sony_ivy#1]
Hi there

Thanks for maintaining these sources.

I am trying to build ivy from your sources, and I am failing on the same issue.

I am likely missing a camera dependency, but have tried a few without success.

Wondered if you might be able to provide any tips as to what I am missing.

Thanks in advance

```
FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/bu>
error: device/sony/kitakami-common/camera/libcameraservice/libcameraservice_fuzzer/Android.bp:32:1: "camera_service_fuzzer_kitakami" depends on undefined mod>
error: device/sony/kitakami-common/camera/libcameraservice/libcameraservice_fuzzer/Android.bp:32:1: "camera_service_fuzzer_kitakami" depends on undefined mod>
ninja: build stopped: subcommand failed.
12:30:57 soong bootstrap failed with: exit status 1
```

```
       > [ 98% 179/182] test android/soong/apex
       > [ 98% 180/182] test android/soong/sdk
       > [ 99% 181/182] cp out/soong/.bootstrap/bin/soong_build
       > [100% 182/182] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
       > FAILED: out/soong/build.ninja
       > out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
       > error: device/sony/kitakami-common/camera/libcameraservice/libcameraservice_fuzzer/Android.bp:32:1: "camera_service_fuzzer_kitakami" depends on undefined module "android.hardware.camera.provider@2.7"
       > error: device/sony/kitakami-common/camera/libcameraservice/libcameraservice_fuzzer/Android.bp:32:1: "camera_service_fuzzer_kitakami" depends on undefined module "android.hardware.camera.device@3.7"

```

**Comment by TARKZiM** [comment]
I think your ROM sources are not synced correctly

See https://github.com/LineageOS/android_hardware_interfaces/blob/lineage-19.1/camera/provider/2.7/Android.bp

**Comment by mannp** [comment]
Apologies, I didn't mention, I am trying to build for Lineage-18.1, and I believe the repos are in sync ... (robotnix on NixOS syncs the repos) and have made a little more progress now, thank you.

I was using your android_hardware_lineage_interfaces, rather than the LineageOS one.

I have now swapped to the LineageOS one and notice the link you show does not exist for 18.1, but only 19.1

I have rebuilt with just android_hardware_lineage_interfaces at branch 19.1 and get a usb trust issue.

```
       > [100% 182/182] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
       > FAILED: out/soong/build.ninja
       > out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
       > error: hardware/lineage/interfaces/trust/Android.bp:15:1: "trust_defaults" depends on undefined module "trust_usb_control_defaults"
       > ninja: build stopped: subcommand failed.
       > 17:16:06 soong bootstrap failed with: exit status 1  
```

I will review this new error, thanks.

I am able to build for my togari, z3c and z3tc devices, but I am stumped on ivy :-/

**Comment by TARKZiM** [comment]
You can't use lineage-19.1 branch for LineageOS 18.1 sources...
Either device trees or other modules.

**Comment by TARKZiM** [comment]
Again, My lineage-19.1 branch device tree CAN NOT be used for compiling LineageOS 18.1 or other Android 11 Roms.
Use lineage-18.1 branch instead...
