### ISSUE TITLE
Charming guy ... please delete me again.

### ISSUE THREAD

**Issue by mannp** [Sony-MSM8994-Dev/android_device_sony_ivy#2]

**Comment by TARKZiM** [comment]
I was telling you the truth, and you gave me an unlike, what's the point of doing this on Github?

**Comment by mannp** [comment]
None at all. 

If you cannot remain professional with queries from people not as familiar with your code as you, then I will surely leave you be.

Deleting posts because you do not like them is your choice of course and I apologise for wasting your time.

The fact that I was building for 18.1 and your answer related ONLY to 19.1 was the reason for the unlike and nothing to do with the questioning of your truth.

**Comment by TARKZiM** [comment]
That means you were using wrong branches to build and I don't think it's needed to keep the "issue" there since the problem isn't really about this REPO.

**Comment by mannp** [comment]
> That means you were using wrong branches to build and I don't think it's needed to keep the "issue" there since the problem isn't really about this REPO.

I was using ONLY your REPO, which did not build for 18.1.

Your answer for it not building was referring me to a 19.1 ONLY branch, not relevant for 18.1.

Appears to be a language barrier, so will leave you be.

**Comment by TARKZiM** [comment]
I mean, because you were using my kitakami-common tree (lineage-19.1) to build so you were facing such errors, then i suggest you to SWITCH to my kitakami-common lineage-18.1 branch to build, isn't that right?
Maybe you misunderstand something.

**Comment by mannp** [comment]
> I mean, because you were using my kitakami-common tree (lineage-19.1) to build so you were facing such errors, then i suggest you to SWITCH to my kitakami-common lineage-18.1 branch to build, isn't that right? Maybe you misunderstand something.

No, it is not right, it is only your narrative.

I was never using a lineage-19.1 branch of any of the dependencies to build lineage-18.1. 

The only person who referred me to a lineage-19.1 ONLY branch was you.
